### ISSUE TITLE
Can not use this api

### ISSUE THREAD

**Issue by Harry-Jing** [barrust/mediawiki#123]
from mediawiki import MediaWiki
wiki = MediaWiki('https://zh.moegirl.org.cn/api.php')

that‘s show is a invalid URL

**Comment by barrust** [comment]
I have tried loading the API link in a normal browser and it isn't loading for me. It could be that the API is not turned on or that it is behind some kind of firewall. 

If it is turned on for the MediaWiki site than you should get a page similar to the Wikipedia API site: https://en.wikipedia.org/w/api.php
