### ISSUE TITLE
How to get the page I requested and not the first one coming up from the search?

### ISSUE THREAD

**Issue by KelSolaar** [barrust/mediawiki#127]
Hello,

Given the following:

```python
API_WIKI_FANDOM = "https://forgottenrealms.fandom.com/api.php"
wiki = MediaWiki(API_WIKI_FANDOM)
print(wiki.search("House of Crystal Storage"))
print(wiki.page("House of Crystal Storage"))
```

```
['City System', 'House of Crystal Storage', 'House of the Moon', 'High Tower of Thalivar', 'Silver dragon', 'Undermountain', 'Mithral Hall', "Baldur's Gate III", 'Easthaven', 'Hellgate Keep']
<MediaWikiPage 'City System'>
```

How do I get the `House of Crystal Storage` page?

It seems like I get the first found by the search API call instead of the actual correct page.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
After looking at the code, I found the `auto_suggest=True` parameter. It might be worth highlighting this behaviour in the docs.

**Comment by barrust** [comment]
perhaps a note would be helpful in the documentation? Any recommendations on the wording?

**Comment by barrust** [comment]
added notes in the documentation
