### ISSUE TITLE
Page sections and table_of_contents become empty for (maybe) all pages in German language?

### ISSUE THREAD

**Issue by tumluliu** [barrust/mediawiki#137]
Hi there, it seems the `.sections` and `.table_of_contents` attributes (not 100% sure if for all German pages) return empty results. E.g.:

```
In [1]: from mediawiki import MediaWiki

In [2]: w = MediaWiki(lang='de')

In [3]: wp = w.page('Frauenkirche (München)', auto_suggest=False)

In [4]: wp.sections
Out[4]: []

In [5]: wp.table_of_contents
Out[5]: OrderedDict()

In [6]: len(wp.table_of_contents)
Out[6]: 0
```

For pages in English and Chinese, they seem ok. Any recent changes from `de` wiki are causing this issue? 

Thanks!

**Comment by barrust** [comment]
It seems to be a problem with what the German Wikipedia is returning. Both the `sections` and `table_of_contents` parses information out of the `contents` property. In the English, the information is still present but not in the German response. Interestingly, the section headers are not in the `content` at all in the German page. 

Specifically, it looks for the following: 

```
== Section Title ==
```

This is currently an issue for Wikipedia.

**Comment by tumluliu** [comment]
Thanks very much for your reply and investigation. That sounds for me a severe bug from de.wikipedia.org 😕. Do you by any chance know where I can report this issue to, or track some existing ticket?

**Comment by barrust** [comment]
I agree! I don't know where to submit it. I found [this link](https://www.mediawiki.org/wiki/How_to_report_a_bug) but it is for MediaWiki, not Wikipedia itself.

**Comment by barrust** [comment]
Any luck or feedback from the MediaWiki foundation on why German is not returning sections?

**Comment by tumluliu** [comment]
Not really :/ The 0-length sections and no table_of_content issues are still there. And I haven't yet figured out where to report it

**Comment by tumluliu** [comment]
This issue is gone already :tada:
