### ISSUE TITLE
Yugipedia gives an error

### ISSUE THREAD

**Issue by firas5673** [barrust/mediawiki#139]
When I try using it with 'https://yugipedia.com/api.php', I get an error saying 

> mediawiki.exceptions.MediaWikiAPIURLError: https://yugipedia.com/api.php is not a valid MediaWiki API URL

Even though they DO use MediaWiki.

**Comment by barrust** [comment]
It looks like this API might require a login. 

The following code, which just tries to get a particular page (Asian-Ensligh), returns a forbidden status code. 
 
``` python
import requests
r = requests.get("https://yugipedia.com/api.php", params={"prop": "extracts|revisions", "explaintext": "", "rvprop": "ids", "action": "query", "titles":"Asian-English"})
print(r.status_code)
```

I could make the exception a bit more specific in the case of a forbidden but I can't know for sure if a username and password are required.

**Comment by barrust** [comment]
see branch [issue-139](https://github.com/barrust/mediawiki/tree/issue-139) for a potential improvement on a forbidden status code
