### ISSUE TITLE
wiki.page() returning the wrong page

### ISSUE THREAD

**Issue by lalquier** [barrust/mediawiki#143]
Hi. Testing this package on a local wiki instance. I am running into an issue with the .page() method.
Let's say I have a page called 'Knowledge Base' and a page called 'Knowledge Base Testing'.
I have defined a wiki object with Mediawiki() and I can test it successfully on random pages or search, but when I try to use:

```p = wiki.page('Knowledge Base)```

The package returns the content of 'Knowledge Base Testing' instead.

It feels like it matches the first instance of the substring of the page title passed in parameter instead of trying to do an exact match.

**Comment by barrust** [comment]
It is likely the auto suggest that the MediaWiki site is returning is being more aggressive than you expect. If you know the name of the page, I would turn the auto_suggest parameter to False. 

Try something like this:

```python
p = wiki.page('Knowledge Base', auto_suggest=False)
print(p.title)

```
