### ISSUE TITLE
Error with sections

### ISSUE THREAD

**Issue by prunacomar** [barrust/mediawiki#145]
Hi there. Using pymediawiki 0.7.4, and getting details for https://es.wikipedia.org/wiki/Louvain-la-Neuve, and trying to query **p.sections** I get the following error:

```
    File "/usr/local/lib/python3.13/site-packages/mediawiki/mediawikipage.py", line 483, in sections
    self._parse_sections()
    ^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.13/site-packages/mediawiki/mediawikipage.py", line 818, in _parse_sections
    path.pop()
    ^^^^^^^^^^
    IndexError: pop from empty list
```

Not sure on the reason. Would it help to check list for existing elements, or catch the exception and manage it? Please let me know if there's suggestion on how to manage it, and I can help with a candidate fix.

**Comment by barrust** [comment]
closed by #146
