### ISSUE TITLE
Category title transformation is language specific (categorytree is broken as a result for non-english languages)

### ISSUE THREAD

**Issue by inktrap** [barrust/mediawiki#48]
The english prefix category:" is removed in mediawiki.py:

~~~
536                 elif rec['type'] == 'subcat':
537                     tmp = rec['title']
538                     if tmp.startswith('Category:'):                                                                                                                                         
539                         tmp = tmp[9:]
540                     subcats.append(tmp)
~~~

This does not work for non-english languages. Categorytree is broken for non-english languages, because each category is prefixed with "Category:".

~~~
606                     try:
607                         categories[cat] = self.page('Category:{0}'.format(cat))
608                         parent_cats = categories[cat].categories                                                                                                                            
609                         links[cat] = self.categorymembers(cat, results=None,
610                                                           subcategories=True)
611                         break
~~~

In e.g. german, this leads to the generation of: ``"Category:Kategorie:Kategorietitel"``. I see three ways (this is why I did not want to create a PR):

 - do not strip/prepend "Category:" and let the user handle it in their language
 - offer defaults and a setting for some languages (five with most articles or something like that?)
 -  query some wikipedia api to get the category prefix in the respective language.

I like it simple, so I would stick with the first solution :)

**Comment by barrust** [comment]
@inktrap thank you for providing this as an issue! I need to think through the different options and consequences of each to changing how we handle prepending "Category:" including breaking users solutions that are already working. I think it may be more than just the category tree that is broken for foreign languages. I will need to look into `categorymemebers` also. 

I think a possible solution to add to the three you mentioned would be to add a new parameter that defaults to `Category` for those that already have what they need but could be changed for other languages, such as German. Something like:

``` python
def categorytree(self, category, depth=5, prefix="Category"):
    # check if prefix has the trailing semicolon or not...
``` 

The `categorymembers` function could do the same. 

How does that sound to you?

**Comment by barrust** [comment]
Would you be able to test out the `hotfix/foreign-categories` branch? All tests still pass and I was able to confirm that it works for all the foreign languages I checked. See #49

To use you just need to set the `prefix` parameter:
``` python
wikipedia = mediawiki.MediaWiki(lang='de')

# category memebers
cats = wikipedia.categorymembers('Titel nach Staat', prefix='Kategorie')
print(cats)

# category tree
cat_tree = wikipedia.categorytree('Titel nach Staat', prefix='Kategorie')
print(cat_tree)
```

**Comment by inktrap** [comment]
I can get a tree now, but found two issues:

~~~
wikipedia.categorytree('Blattgemüse', depth=10, prefix='Kategorie')
~~~

shows that the parent-categories still have the (non-english) prefix:

~~~
'parent-categories': ['Kategorie:Blatt', 'Kategorie:Gemüsepflanze', 'Kategorie:Wildkraut']}}`
~~~

Secondly, even if I specify ``depth=None`` I only get the first level for the german wikipedia (different lang settings not shown here):

~~~
results = wikipedia.categorytree('Blattgemüse', depth=None, prefix='Kategorie')                                                                                                                 
results = wikipedia.categorytree('Leaf_vegetables', depth=None, prefix='Category')
~~~

**Comment by inktrap** [comment]
Thanks for the really fast response btw. ;)

**Comment by inktrap** [comment]
On second thought, wouldn't it be better to optionally provide the category when instantiating``Mediawiki``, like ``lang``? They depend on each other.

**Comment by barrust** [comment]
@inktrap you are absolutely correct that it should be in the initialization of the MediaWiki object. I will try to get to that later today, but it will be much later. If you want to take a stab at that, let me know!

**Comment by barrust** [comment]
Your comment about the category information still in the tree made me think of something that I hadn't before and why you are correct that it should be determined when setting up the MediaWiki object. I found another place where we will need to check in the `mediawikipage.py` file where we also check for the category prefix. I couldn't help myself so I have a branch that implements this. I don't have tests to verify everything but it you would like to see if it works, that would be great. 

(Creating good tests is always the hard part!)

The new branch is `hotfix/foreign-category-tree` if you have time. Any comments would be very helpful (I am not partial to the keyword argument name...) 


``` python
wikipedia = mediawiki.MediaWiki(lang='de', cat_prefix='Kategorie')
cats = wikipedia.categorymembers('Titel nach Staat')
results = wikipedia.categorytree('Blattgemüse', depth=3)
```

**Comment by inktrap** [comment]
While I am now able to get the tree in a non-english wikipedia, I found another issue:

If I am getting some categorytree with a subcategory, like this:

~~~
#!/usr/bin/env python3.6

from mediawiki import mediawiki as mw
import pprint

pp = pprint.PrettyPrinter(indent=4)
wikipedia = mw.MediaWiki(lang='en', cat_prefix='Category')
results = wikipedia.categorytree('Leaf_vegetables', depth=1)
pp.pprint(results)
~~~

I'll get subcategory links that are splitted.
Below is some shortened output of the snippet above. Compare the links of the category [Leaf vegetables](https://en.wikipedia.org/wiki/Category:Leaf_vegetables): ``Leaf_vegetables``, it contains, e.g.:

~~~
'List of leaf vegetables',
~~~

and of the subcategory: [Brassica dishes](https://en.wikipedia.org/wiki/Category:Brassica_dishes), which contains:

~~~
                                                                                     'New '
                                                                                     'England '
                                                                                     'boiled '
                                                                                     'dinner',
~~~

It is clear that it should be ``'New England boiled dinner'``.

~~~
{   'Leaf_vegetables': {   'depth': 0,
                           'links': [   'Leaf vegetable',
                                        'List of leaf vegetables',
                                      ],
                           'parent-categories': ['Leaves', 'Vegetables'],
                           'sub-categories': {   'Brassica dishes': {   'depth': 1,
                                                                        'links': [   'Jiggs '
                                                                                     'dinner',
                                                                                     'Kimchi',
                                                                                     'Lanttulaatikko',
                                                                                     'New '
                                                                                     'England '
                                                                                     'boiled '
                                                                                     'dinner',
                                                                                     'Pot '
                                                                                     'liquor',
                                                                                     'Steckrübeneintopf',
                                                                                     'Woolton '
                                                                                     'pie'],
                                                                        'parent-categories': [   'Brassica',
                                                                                                 'Leaf '
                                                                                                 'vegetables',
                                                                                                 'Prepared '
                                                                                                 'foods '
                                                                                                 'by '
                                                                                                 'main '
                                                                                                 'ingredient',
                                                                                                 'Vegetable '
                                                                                                 'dishes'],
                                                                        'sub-categories': {   'Brassica oleracea dishes': None,
                                                                                              'Cabbage dishes': None,
                                                                                              'Kimchi': None}},
 
~~~

**Comment by barrust** [comment]
Are you sure that isn't a setting in the pprint library? I will try to look at this tonight to ensure that it isn't from pymediawiki but we aren't splitting the results anywhere on our end.

**Comment by barrust** [comment]
I did ensure that that is actually happening due to pprint. Not sure why it is splitting strings, but it isn't that way in the result set. If the original issue is resolved, can we close this out? I will merge the PR.

**Comment by inktrap** [comment]
You are right, it was ``pprint``.

I had a feeling that it might be not a good idea to change the output (because of stuff like this). And it is weird that following links worked, but that they seemed broken at the same time. I don't know why pprint behaves like that but will keep it in mind.

Thanks how well & quickly you handled this issue :)

**Comment by barrust** [comment]
Added to release [0.4.1](https://github.com/barrust/mediawiki/releases/tag/v0.4.1) and uploaded it to [pypi](https://pypi.org/project/pymediawiki/0.4.1/)

**Comment by inktrap** [comment]
> The formatted representation keeps objects on a single line if it can, and breaks them onto multiple lines if they don’t fit within the allowed width.

[pprint](https://docs.python.org/3.6/library/pprint.html)
