### ISSUE TITLE
`MediaWikiPage.section` doesn't return content of section with nested level greater than 2

### ISSUE THREAD

**Issue by shnela** [barrust/mediawiki#64]
`MediaWikiPage.section` doesn't work for section which title is surrounded with more than 3 "=".
E.g. for page page https://en.wikipedia.org/wiki/Napoleon section 
`page.section("Temporary peace in Europe")` returns empty string.

**Comment by barrust** [comment]
Great catch! I have started a fix for this issue that I hope to get out soon!
