### ISSUE TITLE
Implementation of API:Langlinks property

### ISSUE THREAD

**Issue by shnela** [barrust/mediawiki#65]
It would be nice if this library could show you available languages, or event switch page between them using [API:Langlinks property](https://www.mediawiki.org/wiki/API:Langlinks).

I've noticed that simple implementation is very similar to `categories`.
Would you mind if I create PR for this issue?

**Comment by barrust** [comment]
I believe this only returns the links for a specific page in different languages. Perhaps I am misunderstanding what it does. I would love to review a PR for this, if you would like to tackle it!

**Comment by shnela** [comment]
PR is blocked due to #69.

**Comment by barrust** [comment]
resolved by #77
