### ISSUE TITLE
Replacing ''' with """

### ISSUE THREAD

**Issue by shnela** [barrust/mediawiki#68]
According to [Google Styleguide for Python](https://google.github.io/styleguide/pyguide.html#310-strings) docstring should use `"""` instead of `'''`:

> Prefer """ for multi-line strings rather than '''. Projects may choose to use ''' for all non-docstring multi-line strings if and only if they also use ' for regular strings. Docstrings must use """ regardless.

**Comment by barrust** [comment]
I prefer the single tick for strings in python. But thank you for pointing it out!
