### ISSUE TITLE
Mediawiki.allpages(limit=999999999) capped at 500 (?)

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [barrust/mediawiki#78]
Hello there,

I need to get all the pages for a given wiki instance. I tried
```
en_wikipedia.allpages(limit=999999999999)
```
(no query specified - in hopes of having ALL the pages returned) and yet it only returns 500 values (`len()`).

Is it possible to get ALL the pages for a given wiki, please? Perhaps `limit=-1` or `limit=None` to return the entirety of page listing?

Thank you for the really easy-to-use module!

**Comment by barrust** [comment]
Sadly, that is a limitation [set by the wiki](https://www.mediawiki.org/wiki/API:Allpages); the library passes the value you set and tries to pull all the data. If the wiki provides it then it is returned. 

It could be possible to make it so that a user could do the work using the `apfrom` value.

**Comment by peanutbutterandcrackers** [comment]
@barrust - I see. Thank you.

Could the change be made to allow one to use `apfrom`, please? It would be really helpful.

**Comment by barrust** [comment]
Glad it is working for you! If you are scraping that much information, I ***highly*** recommend [setting your own user agent string](https://pymediawiki.readthedocs.io/en/latest/quickstart.html#set-the-user-agent-string)!

**Comment by peanutbutterandcrackers** [comment]
I see. Thank you very much. I will do so.
