### ISSUE TITLE
KeyError: 'extract'

### ISSUE THREAD

**Issue by DinozavrNenarkoman** [barrust/mediawiki#82]
Hello there, i am getting extract key error when i am trying to access "content" or anything other than title of page.

Here is my simple code and url i am trying to access.

```
from mediawiki import MediaWiki
tropwiki=MediaWiki('https://posmotre.li/api.php')

test=tropwiki.page(pageid=4242)
print('found title>'+(test.title))
print('found content>'+(test.content))
```

Here is traceback what i am getting with it.

```
found title>The Elder Scrolls
Traceback (most recent call last):
File "/home/test/suptest.py", line 8, in <module>
    print('found content>'+(test.content))
  File "/home/.local/lib/python3.6/site-packages/mediawiki/mediawikipage.py", line 154, in content
    self._pull_content_revision_parent()
  File "/home/.local/lib/python3.6/site-packages/mediawiki/mediawikipage.py", line 140, in _pull_content_revision_parent
    self._content = page_info["extract"]
KeyError: 'extract'
```

It does success to return page title but errors on content/summary and anything else, is this bug or it is something to do with the url site?
How can i access the pages content or summary on this specific site?

Tested on python3.8 and 3.6
Please check this, i would be grateful to any answer.

**Comment by barrust** [comment]
What API version is being reported by that API URL? It is in a language I can't read! Once we know the api version then we can start to look into if we can support it (if it is old) or if the api has changed. 

```python
from mediawiki import MediaWiki
tropwiki = MediaWiki('https://posmotre.li/api.php')
print(tropwiki.api_version)
```

**Comment by DinozavrNenarkoman** [comment]
It returns "1.29.0"
Is this fine?

**Comment by barrust** [comment]
Actually, that is important! According to the [api page](https://www.mediawiki.org/wiki/Extension:TextExtracts) it says that it must be installed on versions prior to 1.34. Per the sites extensions we can see that it isn't installed:
``` python
from mediawiki import MediaWiki
site = MediaWiki('https://posmotre.li/api.php')
print(site.extensions)
```

We should probably catch that issue of the extension not being installed and not error out.

**Comment by DinozavrNenarkoman** [comment]
Here is what it returns.

```
['Abuse Filter', 'AntiSpoof', 'CheckUser', 'Cite', 'Cologne Blue', 'ConfirmEdit', 'EmbedVideo', 'Interwiki', 'Liquid Threads', 'Modern', 'MonoBook', 'PCR GUI Inserts', 'ParserFunctions', 'ReCaptchaNoCaptcha', 'Renameuser', 'Replace
 Text', 'TorBlock', 'Vector', 'WikiEditor']
```
It seems there is no specific extension here.

**Comment by barrust** [comment]
Yep, the `TextExtracts` extension should be installed for it to work. I could make it so that it either throws a controlled exception or I could make it be an empty string when it isn't available. What do you think would be preferable?

**Comment by DinozavrNenarkoman** [comment]
I think exception would be simpler to understand that something is wrong rather than empty string, well thanks for finding it out. However, is there anyway to get content from site without this extension?
