### ISSUE TITLE
Support for wikibase (powering WIkidata) or explicit documenting it as out of scope would be great

### ISSUE THREAD

**Issue by matkoniecz** [barrust/mediawiki#92]

**Comment by barrust** [comment]
Sorry, I do not know of and have never used wikibase. I see that it is based on mediawiki but am unsure what they are adding on top of the base mediawiki system. What would it require to be able to support wikibase? I think it may be out of scope for this project, but gathering information could be useful. 

Perhaps these libraries would be a better matches for your needs: [wikibase-api](https://pypi.org/project/wikibase-api/) or [python-wikibase](https://pypi.org/project/python-wikibase/)

**Comment by matkoniecz** [comment]
See for example https://www.wikidata.org/wiki/Q513 - entry is not a freeform text with some templates but a machine readable database,

If you are uninterested in it and have no experience with it then it makes no sense to spend time on implementing this.

I think that this issue may be good enough by itself to document this - so maybe it can be simply closed. Or is adding explicit note in a readme a good idea?

**Comment by barrust** [comment]
@matkoniecz I think this is out of scope for this library as everything that would be required would only be useful for these subsets of sites. I am happy to document this, if you have a good way of expressing it. 

This library could be useful in building a parser for wikidata.

**Comment by matkoniecz** [comment]
I opened pull request with my idea how to note it.
